### ISSUE TITLE
Local API error: Playlist - TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#146]
Try to open playlist. After few seconds you should see message 
TypeError: Cannot read property 'name' of null

EDIT:
When I tried play playlist, I saw next message
TypeError: Cannot read property 'formats' of undefined

**Comment by PrestonN** [comment]
It seems the issue is because of the playlist having a private video included.  I've pushed out a fix for this.  If you see the issue again feel free to re-open.

**Comment by pawlosck** [comment]
How to reopen?

This issue wasn't fixed.

Message "TypeError: Cannot read property 'formats' of undefined" is visible in this movie "https://www.youtube.com/watch?v=U29W1ljYPuA"

I saw this message when I tried to play playlist.

**Comment by PrestonN** [comment]
It should stay closed because the issue was in fact, fixed.  The issue had to do with the playlists having issues, which had nothing to do with the other issue you were seeing.  The other issue should have also been a new issue.

If you attempted to play the video you linked on YouTube, you would see that the video is unavailable and cannot be played.  There is nothing I can do about that.  I can however display a better message in the future.
